name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuración de Java y Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      # 3. Construcción del proyecto
      - name: Build with Maven
        run: mvn clean install

      # 4. Ejecución de pruebas unitarias
      - name: Run tests
        run: mvn test

      # 5. Generar reporte de cobertura con JaCoCo
      - name: Generate code coverage report with JaCoCo
        run: mvn jacoco:report

      # 6. Análisis de estilo con Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      # 7. Análisis estático con SpotBugs
      - name: Run SpotBugs
        run: mvn spotbugs:spotbugs
